"""Read and write generated AION cell-library Verilog files.

A cell library produced by ``generate-cells`` is a plain Verilog file holding
one module per mined pattern.  Every module is preceded by a machine-readable
marker::

    // AION canonical_key: N0:sg13g2_nand2|N1:sg13g2_nor2|E0:Y:1:A1|...
    module AION_nand2_nor2_0 ( I0, I1, I2, O0 );
    ...
    endmodule

The marker is what lets ``rewrite`` connect a pattern it just mined to a module
in a file the user may have hand-edited, without depending on module names.
Files that carry no marker (hand-written libraries) fall back to deriving the
key from the module structure with Yosys.

A module whose transistor implementation takes a complemented input from
outside carries a second marker naming the ports concerned::

    // AION complement_inputs: I1
    module AION_inv_nand2_nor2_0 ( I0, I1, I2, O0, I1_bar );

The library is the authority on a module's interface, so that is where the
information lives: ``rewrite`` reads it back to know which extra ports it has
to drive.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from aion_opt.io.cell_lib import CellLib

#: Marker written above each generated module.
KEY_COMMENT_PREFIX = "// AION canonical_key: "

#: Marker naming the input ports whose complement arrives from outside.
COMPLEMENT_COMMENT_PREFIX = "// AION complement_inputs: "

_KEY_RE = re.compile(r"^\s*//\s*AION\s+canonical_key:\s*(.+?)\s*$")
_COMPLEMENT_RE = re.compile(r"^\s*//\s*AION\s+complement_inputs:\s*(.*?)\s*$")
_MODULE_START_RE = re.compile(r"^\s*module\s+(\w+)\b")
_ENDMODULE_RE = re.compile(r"^\s*endmodule\b")


@dataclass
class CellModule:
    """One module of a cell library, with its verbatim source text."""

    name: str
    text: str
    canonical_key: str | None = None
    #: Input ports whose complement is supplied on a ``<port>_bar`` port.
    complement_inputs: tuple[str, ...] = ()

    def render(self) -> str:
        """Return the module text, prefixed by its markers."""
        markers = ""
        if self.canonical_key is not None:
            markers += f"{KEY_COMMENT_PREFIX}{self.canonical_key}\n"
        if self.complement_inputs:
            markers += (
                f"{COMPLEMENT_COMMENT_PREFIX}{' '.join(self.complement_inputs)}\n"
            )
        return markers + self.text


def split_modules(text: str) -> list[CellModule]:
    """Split a cell-library file into its modules.

    Preserves each module verbatim so that a filtered library (see
    :func:`write_library`) is byte-identical to the corresponding slice of the
    full one.
    """
    modules: list[CellModule] = []
    pending_key: str | None = None
    pending_complements: tuple[str, ...] = ()
    current: list[str] | None = None
    current_name = ""

    for line in text.splitlines():
        if current is None:
            key_match = _KEY_RE.match(line)
            if key_match:
                pending_key = key_match.group(1)
                continue
            complement_match = _COMPLEMENT_RE.match(line)
            if complement_match:
                pending_complements = tuple(complement_match.group(1).split())
                continue
            module_match = _MODULE_START_RE.match(line)
            if module_match:
                current = [line]
                current_name = module_match.group(1)
                continue
            # Any other non-blank, non-comment line invalidates a pending key.
            stripped = line.strip()
            if stripped and not stripped.startswith("//"):
                pending_key = None
                pending_complements = ()
            continue

        current.append(line)
        if _ENDMODULE_RE.match(line):
            modules.append(
                CellModule(
                    name=current_name,
                    text="\n".join(current) + "\n",
                    canonical_key=pending_key,
                    complement_inputs=pending_complements,
                )
            )
            current = None
            pending_key = None
            pending_complements = ()

    return modules


def write_library(
    path: Path,
    modules: list[CellModule],
    header: str = "",
) -> None:
    """Write ``modules`` to ``path`` as a Verilog cell library."""
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(module.render() for module in modules)
    path.write_text(header + body, encoding="utf-8")


def library_header(title: str, notes: list[str] | None = None) -> str:
    """Build the comment header written at the top of a cell library."""
    lines = [f"// {title}", "// Automatically generated by aion_opt"]
    lines += [f"// {note}" for note in notes or []]
    return "\n".join(lines) + "\n\n"


def read_keys(path: Path) -> dict[str, str]:
    """Return ``{canonical key: module name}`` from the embedded markers.

    Empty when the file carries no markers.
    """
    return {
        module.canonical_key: module.name
        for module in split_modules(path.read_text(encoding="utf-8"))
        if module.canonical_key
    }


def read_complement_ports(path: Path) -> dict[str, list[str]]:
    """Return ``{module name: input ports taking an external complement}``.

    Empty for a library whose modules build their own inverters.
    """
    return {
        module.name: list(module.complement_inputs)
        for module in split_modules(path.read_text(encoding="utf-8"))
        if module.complement_inputs
    }


def derive_keys(path: Path, cell_lib: "CellLib") -> dict[str, str]:
    """Derive ``{canonical key: module name}`` from module structure via Yosys.

    Fallback for hand-written libraries with no ``canonical_key`` markers.  Each
    module is elaborated on its own and treated as a pattern whose boundary is
    the module's port list -- exactly how the miner sees the same group of cells
    inside the design.
    """
    from aion_opt.graph.builder import build_signal_flow_graph
    from aion_opt.io.verilog_to_json import verilog_to_json_all_modules
    from aion_opt.io.yosys_json import load_yosys_json
    from aion_opt.pattern.subgraph import build_pattern

    json_path = verilog_to_json_all_modules(path)
    keys: dict[str, str] = {}
    try:
        with open(json_path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        for module_name in data.get("modules", {}):
            circuit = load_yosys_json(
                json_path, cell_lib=cell_lib, top_module=module_name
            )
            if not circuit.instances:
                continue
            sfg = build_signal_flow_graph(circuit, cell_lib)
            pattern = build_pattern(
                circuit,
                set(circuit.instances),
                cell_lib.collapse_name,
                sfg.pin_edges,
            )
            if pattern.canonical_key:
                keys[pattern.canonical_key] = module_name
    finally:
        json_path.unlink(missing_ok=True)
    return keys


def load_key_map(path: Path, cell_lib: "CellLib") -> dict[str, str]:
    """Return ``{canonical key: module name}`` for a cell library.

    Uses the embedded markers when present and falls back to structural
    derivation otherwise.
    """
    keys = read_keys(path)
    if keys:
        return keys
    return derive_keys(path, cell_lib)
