"""Write an internal Circuit to a structural Verilog netlist."""

from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from aion_opt.graph.circuit import Circuit


CONST_NAMES = {
    "0": "1'b0",
    "1": "1'b1",
    "x": "1'bx",
    "z": "1'bz",
}

# Characters that are illegal in a Verilog identifier.
_ILLEGAL_ID = re.compile(r"[^A-Za-z0-9_$]")


def _sanitize(name: str) -> str:
    """Return a valid Verilog identifier for a net/instance name."""
    sanitized = _ILLEGAL_ID.sub("_", name)
    if sanitized and sanitized[0].isdigit():
        sanitized = "_" + sanitized
    return sanitized or "_unnamed_"


def _bit_to_verilog(
    bit: int | str,
    bit_to_net: dict[int, str],
    bit_to_port_slice: dict[int, str],
) -> str:
    if isinstance(bit, str):
        return CONST_NAMES.get(bit, f"1'b{bit}")
    if bit in bit_to_port_slice:
        return bit_to_port_slice[bit]
    return bit_to_net.get(bit, f"_bit_{bit}_")


def _collect_net_names(circuit: "Circuit") -> dict[int, str]:
    """Map every signal bit to its preferred net name (sanitized)."""
    bit_to_net: dict[int, str] = {}

    # Named nets first; prefer non-auto, non-port names.
    def priority(net_name: str) -> int:
        if net_name.startswith("_auto_"):
            return 2
        # Port names are handled via slices; give them low priority here.
        if any(net_name == p.name for p in circuit.ports):
            return 1
        return 0

    for net_name, net in sorted(
        circuit.nets.items(), key=lambda item: priority(item[0])
    ):
        sanitized = _sanitize(net_name)
        for bit in net.bits:
            if isinstance(bit, int) and bit not in bit_to_net:
                bit_to_net[bit] = sanitized

    return bit_to_net


def _collect_port_slices(circuit: "Circuit") -> dict[int, str]:
    """Map port bits to Verilog slice expressions like p[3]."""
    bit_to_slice: dict[int, str] = {}
    for port in circuit.ports:
        if port.width == 1:
            bit = port.bits[0]
            if isinstance(bit, int):
                bit_to_slice[bit] = port.name
        else:
            for idx, bit in enumerate(port.bits):
                if isinstance(bit, int):
                    bit_to_slice[bit] = f"{port.name}[{idx}]"
    return bit_to_slice


def _format_connections(
    connections: dict[str, list[int | str]],
    bit_to_net: dict[int, str],
    bit_to_port_slice: dict[int, str],
) -> list[str]:
    """Format pin connections as `.PIN(net)` strings."""
    items: list[str] = []
    for pin in sorted(connections.keys()):
        bits = connections[pin]
        if len(bits) == 1:
            net_expr = _bit_to_verilog(bits[0], bit_to_net, bit_to_port_slice)
        else:
            net_expr = "{" + ", ".join(
                _bit_to_verilog(b, bit_to_net, bit_to_port_slice) for b in bits
            ) + "}"
        items.append(f".{pin}({net_expr})")
    return items


def write_verilog(circuit: "Circuit", path: Path) -> None:
    """Emit a single-module Verilog netlist for the circuit."""
    path.parent.mkdir(parents=True, exist_ok=True)

    bit_to_net = _collect_net_names(circuit)
    bit_to_port_slice = _collect_port_slices(circuit)

    lines: list[str] = []
    lines.append("/* Generated by aion_opt graph2verilog */")
    lines.append("")

    # Module header.
    port_names = [p.name for p in circuit.ports]
    lines.append(f"module {circuit.name} (")
    for i, pname in enumerate(port_names):
        tail = "," if i < len(port_names) - 1 else ""
        lines.append(f"    {pname}{tail}")
    lines.append(");")
    lines.append("")

    # Port declarations.
    for port in circuit.ports:
        if port.width > 1:
            lines.append(f"  {port.direction} [{port.width - 1}:0] {port.name};")
            lines.append(f"  wire [{port.width - 1}:0] {port.name};")
        else:
            lines.append(f"  {port.direction} {port.name};")
            lines.append(f"  wire {port.name};")
    lines.append("")

    # Internal wires.
    declared: set[str] = set(port_names)
    wire_names: set[str] = set()
    for net in circuit.nets.values():
        if net.is_constant():
            continue
        name = _sanitize(net.name)
        if name in declared:
            continue
        wire_names.add(name)

    # Include auto-generated / bit-level names that are still used.
    for inst in circuit.instances.values():
        for bits in inst.connections.values():
            for bit in bits:
                if isinstance(bit, int):
                    name = bit_to_net.get(bit)
                    if name and name not in declared and name not in wire_names:
                        wire_names.add(name)

    for name in sorted(wire_names):
        lines.append(f"  wire {name};")
    if wire_names:
        lines.append("")

    # Instances.
    for inst in sorted(circuit.instances.values(), key=lambda i: i.name):
        conns = _format_connections(
            inst.connections, bit_to_net, bit_to_port_slice
        )
        lines.append(f"  {inst.cell_type} {inst.name} (")
        for i, conn in enumerate(conns):
            tail = "," if i < len(conns) - 1 else ""
            lines.append(f"    {conn}{tail}")
        lines.append("  );")
        lines.append("")

    lines.append("endmodule")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
