// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_a21o_and2_xor2_0 ( I0, I1, I2, I3, I4, O0, O1, O2);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input I4;
  wire I4;
  output O0;
  wire O0;
  output O1;
  wire O1;
  output O2;
  wire O2;


  sg13g2_and2_1 g0 (
    .A(I0),    .B(I1),    .X(O0)  );
  sg13g2_a21o_1 g1 (
    .A1(I2),    .A2(O0),    .B1(O2),    .X(O1)  );
  sg13g2_xor2_1 g2 (
    .A(I3),    .B(I4),    .X(O2)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_a21o_and2_xor2_1 ( I0, I1, I2, I3, I4, O0, O1);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input I4;
  wire I4;
  output O0;
  wire O0;
  output O1;
  wire O1;

  wire w0;

  sg13g2_xor2_1 g0 (
    .A(I0),    .B(I1),    .X(O0)  );
  sg13g2_a21o_1 g1 (
    .A1(I2),    .A2(I3),    .B1(O0),    .X(w0)  );
  sg13g2_and2_1 g2 (
    .A(I4),    .B(w0),    .X(O1)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_and4_nand4_xnor2_2 ( I0, I1, I2, I3, I4, I5, I6, I7, O0, O1, O2);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input I4;
  wire I4;
  input I5;
  wire I5;
  input I6;
  wire I6;
  input I7;
  wire I7;
  output O0;
  wire O0;
  output O1;
  wire O1;
  output O2;
  wire O2;


  sg13g2_and4_1 g0 (
    .A(I0),    .B(I1),    .C(I2),    .D(I3),    .X(O0)  );
  sg13g2_xnor2_1 g1 (
    .A(I4),    .B(O0),    .Y(O1)  );
  sg13g2_nand4_1 g2 (
    .A(I5),    .B(I6),    .C(I7),    .D(O0),    .Y(O2)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_a21oi_inv_o21ai_3 ( I0, I1, I2, I3, O0, O1);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  output O0;
  wire O0;
  output O1;
  wire O1;

  wire w0;

  sg13g2_inv_1 g0 (
    .A(I0),    .Y(O0)  );
  sg13g2_o21ai_1 g1 (
    .A1(O0),    .A2(I1),    .B1(I2),    .Y(w0)  );
  sg13g2_a21oi_1 g2 (
    .A1(O0),    .A2(I3),    .B1(w0),    .Y(O1)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_a22oi_nand4_o21ai_4 ( I0, I1, I2, I3, I4, I5, I6, I7, I8, O0, O1);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input I4;
  wire I4;
  input I5;
  wire I5;
  input I6;
  wire I6;
  input I7;
  wire I7;
  input I8;
  wire I8;
  output O0;
  wire O0;
  output O1;
  wire O1;

  wire w0;

  sg13g2_nand4_1 g0 (
    .A(I0),    .B(I1),    .C(I2),    .D(I3),    .Y(w0)  );
  sg13g2_o21ai_1 g1 (
    .A1(I4),    .A2(w0),    .B1(I5),    .Y(O0)  );
  sg13g2_a22oi_1 g2 (
    .A1(I6),    .A2(I7),    .B1(w0),    .B2(I8),    .Y(O1)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_inv_nor2_nor3_5 ( I0, I1, I2, I3, O0, O1, O2);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  output O0;
  wire O0;
  output O1;
  wire O1;
  output O2;
  wire O2;


  sg13g2_inv_1 g0 (
    .A(I0),    .Y(O0)  );
  sg13g2_nor2_1 g1 (
    .A(O0),    .B(I1),    .Y(O1)  );
  sg13g2_nor3_1 g2 (
    .A(O0),    .B(I2),    .C(I3),    .Y(O2)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_and2_nand2_nand3_6 ( I0, I1, I2, I3, I4, O0, O1);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input I4;
  wire I4;
  output O0;
  wire O0;
  output O1;
  wire O1;

  wire w0;

  sg13g2_nand3_1 g0 (
    .A(I0),    .B(I1),    .C(I2),    .Y(w0)  );
  sg13g2_and2_1 g1 (
    .A(w0),    .B(I3),    .X(O0)  );
  sg13g2_nand2_1 g2 (
    .A(I4),    .B(w0),    .Y(O1)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_a22oi_nand2_7 ( I0, I1, I2, I3, I4, I5, O0);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input I4;
  wire I4;
  input I5;
  wire I5;
  output O0;
  wire O0;

  wire w0;
  wire w1;

  sg13g2_nand2_1 g0 (
    .A(I0),    .B(I1),    .Y(w0)  );
  sg13g2_nand2_1 g1 (
    .A(w0),    .B(w1),    .Y(O0)  );
  sg13g2_a22oi_1 g2 (
    .A1(I2),    .A2(I3),    .B1(I4),    .B2(I5),    .Y(w1)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_nand2_nand3_8 ( I0, I1, I2, I3, I4, O0, O1);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input I4;
  wire I4;
  output O0;
  wire O0;
  output O1;
  wire O1;

  wire w0;

  sg13g2_nand2_1 g0 (
    .A(I0),    .B(I1),    .Y(w0)  );
  sg13g2_nand2_1 g1 (
    .A(w0),    .B(O1),    .Y(O0)  );
  sg13g2_nand3_1 g2 (
    .A(I2),    .B(I3),    .C(I4),    .Y(O1)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_a21oi_nor2_9 ( I0, I1, I2, I3, O0);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  output O0;
  wire O0;

  wire w0;

  sg13g2_a21oi_1 g0 (
    .A1(I0),    .A2(I1),    .B1(I2),    .Y(w0)  );
  sg13g2_nor2_1 g1 (
    .A(w0),    .B(I3),    .Y(O0)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_a22oi_inv_10 ( I0, I1, I2, I3, O0);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  output O0;
  wire O0;

  wire w0;

  sg13g2_a22oi_1 g0 (
    .A1(I0),    .A2(I1),    .B1(I2),    .B2(I3),    .Y(w0)  );
  sg13g2_inv_1 g1 (
    .A(w0),    .Y(O0)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_nand2_11 ( I0, I1, I2, O0);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  output O0;
  wire O0;

  wire w0;

  sg13g2_nand2_1 g0 (
    .A(I0),    .B(I1),    .Y(w0)  );
  sg13g2_nand2_1 g1 (
    .A(w0),    .B(I2),    .Y(O0)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_a22oi_nor2_12 ( I0, I1, I2, I3, I4, I5, I6, I7, O0, O1, O2);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input I4;
  wire I4;
  input I5;
  wire I5;
  input I6;
  wire I6;
  input I7;
  wire I7;
  output O0;
  wire O0;
  output O1;
  wire O1;
  output O2;
  wire O2;


  sg13g2_nor2_1 g0 (
    .A(I0),    .B(I1),    .Y(O0)  );
  sg13g2_a22oi_1 g1 (
    .A1(I2),    .A2(I3),    .B1(O0),    .B2(I4),    .Y(O1)  );
  sg13g2_a22oi_1 g2 (
    .A1(I5),    .A2(I6),    .B1(O0),    .B2(I7),    .Y(O2)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_a21oi_o21ai_13 ( I0, I1, I2, I3, I4, O0);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input I4;
  wire I4;
  output O0;
  wire O0;

  wire w0;

  sg13g2_o21ai_1 g0 (
    .A1(I0),    .A2(I1),    .B1(I2),    .Y(w0)  );
  sg13g2_a21oi_1 g1 (
    .A1(I3),    .A2(I4),    .B1(w0),    .Y(O0)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_nand2_nand3_nor2b_14 ( I0, I1, I2, I3, I4, O0, O1);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input I4;
  wire I4;
  output O0;
  wire O0;
  output O1;
  wire O1;

  wire w0;

  sg13g2_nand3_1 g0 (
    .A(I0),    .B(I1),    .C(I2),    .Y(w0)  );
  sg13g2_nor2b_1 g1 (
    .A(I3),    .B_N(w0),    .Y(O0)  );
  sg13g2_nand2_1 g2 (
    .A(I4),    .B(w0),    .Y(O1)  );

endmodule
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
// Auto-generated by aion_opt — do not edit manually

module AION_nand2_nand2b_nand3_15 ( I0, I1, I2, I3, I4, O0, O1);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input I4;
  wire I4;
  output O0;
  wire O0;
  output O1;
  wire O1;

  wire w0;

  sg13g2_nand3_1 g0 (
    .A(I0),    .B(I1),    .C(I2),    .Y(w0)  );
  sg13g2_nand2b_1 g1 (
    .A_N(I3),    .B(w0),    .Y(O0)  );
  sg13g2_nand2_1 g2 (
    .A(I4),    .B(w0),    .Y(O1)  );

endmodule

module AION_inv_nand2_nor2_16 ( I0, I1, I2, O0);

  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  output O0;
  wire O0;

  wire w0;
  wire w1;

  sg13g2_inv_1 g0 (
    .A(I0),    .Y(w0)  );
  sg13g2_nand2_1 g1 (
    .A(w0),    .B(I1),    .Y(w1)  );
    sg13g2_nor2_1 g2 (
    .A(w1),    .B(I2),    .Y(O0)  );

endmodule